import { randomUUID } from "node:crypto";

export const policies = [
  {
    id: "pol-1",
    name: "Refund Request Handler",
    description: "Handles customer refund requests for billing disputes",
    status: "active",
    categories: [
      { id: "cat-1", label: "Billing" },
      { id: "cat-2", label: "Refunds" },
      { id: "cat-3", label: "Escalation" },
    ],
    updatedAt: "2026-02-28T14:30:00.000Z",
    createdAt: "2026-01-15T08:00:00.000Z",
  },
  {
    id: "pol-2",
    name: "Account Recovery",
    description: "Guides users through account recovery and password resets",
    status: "active",
    categories: [
      { id: "cat-4", label: "Security" },
      { id: "cat-5", label: "Authentication" },
    ],
    updatedAt: null,
    createdAt: "2026-02-01T10:00:00.000Z",
  },
  {
    id: "pol-3",
    name: "Onboarding Flow v2",
    description: "New customer onboarding — still being configured",
    status: "draft",
    categories: [
      { id: "cat-6", label: "Onboarding" },
    ],
    updatedAt: "2026-03-01T09:00:00.000Z",
    createdAt: "2026-03-01T09:00:00.000Z",
  },
  {
    id: "pol-4",
    name: "Shipping Status Bot",
    description: "Answers shipping and delivery status questions",
    status: "active",
    categories: [
      { id: "cat-7", label: "Logistics" },
      { id: "cat-8", label: "Tracking" },
    ],
    updatedAt: "2026-02-20T16:45:00.000Z",
    createdAt: "2026-01-28T12:00:00.000Z",
  },
  {
    id: "pol-5",
    name: "Legacy Returns Policy",
    description: "Old returns handling — no longer in use",
    status: "archived",
    categories: [
      { id: "cat-2", label: "Refunds" },
    ],
    updatedAt: "2026-01-10T08:00:00.000Z",
    createdAt: "2025-11-05T14:00:00.000Z",
  },
];

export const testCases = [
  {
    id: "test-1",
    policyId: "pol-1",
    name: "Happy path refund",
    category: "Billing",
    prompt: "Hi, I was charged twice for my subscription. Can I get a refund?",
    expectedSentiment: "negative",
    expectedKeywords: ["refund", "process"],
    status: "passed",
    score: 87.5,
    agentResponse: "I understand you were double-charged. I've initiated a refund for the duplicate charge. You should see it within 3-5 business days.",
    createdAt: "2026-02-20T10:00:00.000Z",
  },
  {
    id: "test-2",
    policyId: "pol-1",
    name: "Angry customer escalation",
    category: "Escalation",
    prompt: "This is ridiculous! I've been waiting 3 weeks for my refund and nobody is helping me!",
    expectedSentiment: "negative",
    expectedKeywords: ["escalate", "manager"],
    status: "failed",
    score: 0,
    agentResponse: "I apologize for the delay. Let me check the status of your refund right away.",
    createdAt: "2026-02-22T14:30:00.000Z",
  },
  {
    id: "test-3",
    policyId: "pol-1",
    name: "Refund eligibility check",
    category: "Refunds",
    prompt: "I bought a product 45 days ago and want a refund. Am I still eligible?",
    expectedSentiment: "neutral",
    expectedKeywords: ["policy", "days", "eligible"],
    status: "pending",
    score: null,
    agentResponse: null,
    createdAt: "2026-03-01T09:15:00.000Z",
  },
  {
    id: "test-6",
    policyId: "pol-2",
    name: "Password reset happy path",
    category: "Authentication",
    prompt: "I forgot my password and can't log in to my account",
    expectedSentiment: "neutral",
    expectedKeywords: ["reset", "email", "link"],
    status: "passed",
    score: 88.3,
    agentResponse: "I can help you reset your password. I've sent a reset link to the email address on file.",
    createdAt: "2026-02-18T09:00:00.000Z",
  },
  {
    id: "test-4",
    policyId: "pol-4",
    name: "Basic tracking query",
    category: "Tracking",
    prompt: "Where is my order #12345?",
    expectedSentiment: "neutral",
    expectedKeywords: ["tracking", "status"],
    status: "passed",
    score: 91.2,
    agentResponse: "Your order #12345 is currently in transit. Expected delivery is March 8th.",
    createdAt: "2026-02-25T11:00:00.000Z",
  },
  {
    id: "test-5",
    policyId: "pol-4",
    name: "Lost package",
    category: "Logistics",
    prompt: "My package was marked as delivered but I never received it",
    expectedSentiment: "negative",
    expectedKeywords: ["investigation", "replacement"],
    status: "running",
    score: null,
    agentResponse: null,
    createdAt: "2026-03-05T16:00:00.000Z",
  },
];

export function createTestCase(policyId, data) {
  const test = {
    id: randomUUID(),
    policyId,
    name: data.name,
    category: data.category,
    prompt: data.prompt,
    expectedSentiment: data.expectedSentiment,
    expectedKeywords: data.expectedKeywords || [],
    status: "pending",
    score: null,
    agentResponse: null,
    createdAt: new Date().toISOString(),
  };
  testCases.push(test);
  return test;
}
